import './i18n.js';
import './theme.js';
import './navbar.js';
import './project-data.js';
import './projects-tiles.js';
import './skills-tiles.js';
import './navbar.js';
import './animations.js';
import './contact.js';